version: 2
jobs:
  build6:
    working_directory: ~/ibankapp-base
    docker:
      - image: openjdk:6
    steps:
      - checkout
      - run: export TERM="dumb";./gradlew check
      - run: bash <(curl -s https://codecov.io/bash) -t 0a1b86f4-6abf-4c46-a263-6af680efbf0f

  build7:
    working_directory: ~/ibankapp-base
    docker:
      - image: oracle/openjdk:7
    steps:
      - checkout
      - run: export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8;export TERM="dumb";./gradlew check

  build8:
      working_directory: ~/ibankapp-base
      docker:
        - image: openjdk:8
      steps:
        - checkout
        - run: export TERM="dumb";./gradlew check
        - run: bash <(curl -s https://codecov.io/bash) -t 0a1b86f4-6abf-4c46-a263-6af680efbf0f

workflows:
  version: 2
  builds:
    jobs:
      - build8
